// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Transport_2D
NumericVector Transport_2D(const NumericMatrix& X);
RcppExport SEXP _CGALTri_Transport_2D(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(Transport_2D(X));
    return rcpp_result_gen;
END_RCPP
}
// Delaunay_Tri_2D
List Delaunay_Tri_2D(const NumericMatrix& data, const NumericVector& bCoord);
RcppExport SEXP _CGALTri_Delaunay_Tri_2D(SEXP dataSEXP, SEXP bCoordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type bCoord(bCoordSEXP);
    rcpp_result_gen = Rcpp::wrap(Delaunay_Tri_2D(data, bCoord));
    return rcpp_result_gen;
END_RCPP
}
// Regular_Tri_2D
List Regular_Tri_2D(const NumericMatrix& data, const NumericVector& bCoord);
RcppExport SEXP _CGALTri_Regular_Tri_2D(SEXP dataSEXP, SEXP bCoordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type bCoord(bCoordSEXP);
    rcpp_result_gen = Rcpp::wrap(Regular_Tri_2D(data, bCoord));
    return rcpp_result_gen;
END_RCPP
}
// Regular_Tri_3D
NumericMatrix Regular_Tri_3D(const NumericMatrix& data);
RcppExport SEXP _CGALTri_Regular_Tri_3D(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Regular_Tri_3D(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CGALTri_Transport_2D", (DL_FUNC) &_CGALTri_Transport_2D, 1},
    {"_CGALTri_Delaunay_Tri_2D", (DL_FUNC) &_CGALTri_Delaunay_Tri_2D, 2},
    {"_CGALTri_Regular_Tri_2D", (DL_FUNC) &_CGALTri_Regular_Tri_2D, 2},
    {"_CGALTri_Regular_Tri_3D", (DL_FUNC) &_CGALTri_Regular_Tri_3D, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CGALTri(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
