# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cropped_Voronoi_2D <- function(data, bCoord) {
    .Call(`_CGALTri_Cropped_Voronoi_2D`, data, bCoord)
}

test_tri <- function(data) {
    .Call(`_CGALTri_test_tri`, data)
}

