# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Transport_2D <- function(X, maxit) {
    .Call(`_CGALTri_Transport_2D`, X, maxit)
}

Delaunay_Tri_2D <- function(data, bCoord) {
    .Call(`_CGALTri_Delaunay_Tri_2D`, data, bCoord)
}

Regular_Tri_2D <- function(data, bCoord) {
    .Call(`_CGALTri_Regular_Tri_2D`, data, bCoord)
}

Regular_Tri_3D <- function(data) {
    .Call(`_CGALTri_Regular_Tri_3D`, data)
}

